name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository content
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Ensure the content is ready (this step is optional)
      - name: Prepare content
        run: |
          echo "Site is ready for deployment"

      # Step 3: Deploy by pushing to the main branch (no need to deploy to gh-pages)
      # Since GitHub Pages is using the main branch, no additional action is needed here
