name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository content
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages using the peaceiris action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Target branch for GitHub Pages
          publish_dir: ./  # Folder containing your static website files (root folder in this case)
